- docs/changes.rst
- nebu/cli/main.py
- nebu/tests/cli/test_main.py
This allows the 'get' command to use the same temporary environment
variables to manipulate the url, thus modifying the origin of the data.
Fixes #11
> Fix to 'get' command to allow url manipulation

- docs/changes.rst
- nebu/cli/main.py
- nebu/tests/cli/test_main.py
- requirements/main.txt
Addresses part of #10. This specifically attempts to answer the question, "What version am I using?"
```sh
> neb --version
Nebuchadnezzar version 1.2.0+1.g16a1bfa
```
> Add a '--version' option to show the currently installed version

- docs/changes.rst
- nebu/cli/main.py
- nebu/tests/cli/test_main.py
The adjustment adds some to to the output. This tells the user that a backup will be made and where the backup file has been written.
```
$ neb config-atom
A backup of your atom-config will be created.
However, this will overwrite your config... continue? [y/N]: y
Wrote backup to /Users/pumazi/.atom/config.cson.bak
Wrote /Users/pumazi/.atom/config.cson
```
> Save a backup file for config-atom command

- .coveragerc
- Makefile
This change set omits the testing modules from the coverage and automates the coverage report creation by adding options to the test running command line.
> Touchup coverage procedures

- docs/changes.rst
- nebu/cli/main.py
- nebu/tests/cli/test_main.py
Slight clarification to error message when trying to `neb get` into an existing directory with the same name. Discussed with @Bkblodget.
> update error messaging when trying to get into existing directory

- docs/changes.rst
- nebu/cli/main.py
- nebu/tests/cli/test_main.py
Now that `get` and `publish` require an `env` argument, provide a way to list valid environment tags
> Implement list-of-valid-environments command

- docs/changes.rst
- nebu/cli/main.py
- nebu/tests/cli/test_main.py
Change /api/v3/publish to /api/publish-litezip, because the OpenStax developer community is favoring api versioning by HTTP header. This doesn't actually go so far as to add the version http header, but that's not important at the moment. This adjustment is to make this major change prior to initial release.
> Change the Press api route from /api/v3/publish to /api/publish-litezip

- docs/changes.rst
- nebu/cli/main.py
- nebu/tests/cli/test_main.py
This no longer relies on the 'latest' specifier, which has the issue of
requesting a cached completezip.
Addresses #44 and #46
> Fix the 'get' command to request a specific version of the completezip

- docs/changes.rst
- nebu/cli/main.py
- nebu/tests/cli/test_main.py
Move all subcommand common options to the subcommands:
``neb [OPTIONS] get [OPTIONS] ...`` becomes ``neb get [OPTIONS``.
For example, ``neb -v get ...`` becomes ``neb get -v ...``.
> Move the verbose option to the subcommands for consistent usage

- docs/changes.rst
- nebu/cli/publish.py
- nebu/tests/cli/test_publish.py
Since we are using atom to do validation, this option simply allows us to skip over the validation when publishing. With this option enabled, you should see a significant speed increase. I'd guess this will specifically help in testing and development. 
Example usage, `neb publish --skip-validation qa . "foo"`
> Add a skip-validation option flag to the publish command

- docs/changes.rst
- nebu/config.py
- nebu/tests/test_config.py
> Fix FileNotFoundError when ~/.config doesn't exist

- .pre-commit-config.yaml
This puts in a configuration for https://pre-commit.com/. You can use this config by running `pre-commit install` (after pre-commit is installed of course).
I've been using this on Press for several weeks now. It particularly helps prevent the miscellaneous pep8 error from popping up on travis.
> Add pre-commit configuration for IDE agnostic styling checks and correction

- docs/changes.rst
- nebu/config.py
- nebu/tests/test_config.py
Simply adds the content*.cnx.org environments to the default configuration file.
See also https://trello.com/c/N4CerCBv/
> Add content environs to the default config

- docs/changes.rst
- nebu/cli/validate.py
- nebu/tests/cli/test_validate.py
New cnxml has a newer jing that returns better error messages. This updates those, as well as allowing validation in a directory that is not a child of the current directory. (displaying error messages blew up trying to shorten the path)
requires cnxml >= v2.1.1-1-ge661791
> Update cnxml for >=2.2.0

- README.rst
Update readme.
1. Instruct devs to install `virtualenv`.
~2. Specifying a specific Python version isn't necessary, and if you specify an incorrect version, the `virtualenv` command will fail, so remove it from the README.~
> Update readme, instruct to install virtualenv

- docs/changes.rst
- nebu/cli/publish.py
- nebu/tests/data/invalid_collection/mux/index.cnxml
- requirements/main.txt
moving models into litezip was not _quite_ completely compatible w/ the models previously used here
for resources: res.name -> res.filename (as well as where the module id is aquired)
> fixup to match litezip 1.5

- docs/changes.rst
- nebu/config.py
- nebu/tests/test_config.py
This adds the staged.cnx.org environment to the default config. This will be used by cnx-automation test against this environment.
> Add the staged.cnx.org environment to the default config file

- nebu/cli/get.py
Since upstream doesn't usually use it, leading to every single XML file being marked as modified. Oops.
> Don't add an xml-declaration when we get XML

- docs/changes.rst
- nebu/cli/cnxml_to_html.py
- nebu/cli/main.py
- nebu/tests/cli/test_cnxml_to_html.py
- requirements/main.txt
Given a collection directory, use ~cnx-db~ cnx-transforms `cnxml_to_full_html` to
transform all the `index.cnxml` to `index.cnxml.html`.
---
I don't know how people feel about `cnxml2html` vs `cnxml-to-html` or something else.  I'm open to suggestions.
Depends on https://github.com/openstax/cnx-db/pull/174 and https://github.com/openstax/cnx-archive/pull/625
**NOTE:** Remove the last commit :skull_and_crossbones:  before merge.
> Add cnxml-to-html command to transform index.cnxml to html

- nebu/cli/assemble.py
- nebu/cli/main.py
- nebu/tests/cli/test_assemble.py
- nebu/tests/data/assembled_collection_for_bakedpdf_workflow/collection.assembled.xhtml
- nebu/tests/data/assembled_collection_for_bakedpdf_workflow/rebuild.py
- nebu/tests/test_utils.py
- nebu/utils.py
- requirements/test.txt
This produces a single-page-html file from a litezip structured
set of data that is first converted from cnxml to html and then
assembled into a single html file.
The interface for this looks like the following:
```sh
$ neb get -r prod col11562 1.23.21
...
$ neb assemble --help
$ neb assemble col11562_1.23.21 workspace
```
Where `col11562_1.23.21` is the directory containing the acquired data from `neb get ...` and `build` is the user defined output directory for the assembled results.
I'm honestly not sure what's wanted as far as the output from the command goes. So the minimum has been put in. Rather than waste time testing for command output that is likely to change anyway, I'll defer to providing as little output as possible until *future feedback* is given to define how the command's …
>  Add the assemble command to produce a single-page-html file 

- nebu/cli/main.py
- nebu/cli/mathify.py
- nebu/tests/cli/test_mathify.py
- nebu/tests/data/test_collection.xhtml
- requirements/main.txt
This branch is based on [fix_imgs_in_collhtml](https://github.com/openstax/nebuchadnezzar/tree/fix_imgs_in_collhtml) because it calls the `neb assemble` command if the input file `collection.xhtml` doesn't exist.
The "neb mathify" command uses docker to run [baked-pdf](https://github.com/openstax/baked-pdf) to transform the math in `collection.xhtml` to svg (by default) or html.  The output is in `collection.mathified.xhtml`.
~There are no tests yet but I'm working on them now.~  Have a look at the code and let me know what you think, thanks!
> Add "neb mathify" command

- nebu/models/utils.py
- nebu/tests/models/test_utils.py
- requirements/main.txt
We were not previously transforming the summary text during model
instantiation. This was causing issues with some content that had math in the
summary. The problem was specifically related to the `<m:...` namespace not
being defined. In terms of HTML this isn't an issue, but the problem was
none of that content was being transformed to HTML, not just the math.
This pulls in an updated cnx-transforms and cnx-epub to complete this work.
The versions have been constrained because version prior to that do not
contain the necessary imports.
This addresses openstax/cnx#290. I've been able to work through that case
without issues. I'd call it resolved.
> Fix to transform the summary text during assembly

- nebu/cli/get.py
- nebu/tests/cli/test_get.py
- nebu/tests/data/unicode.cnxml
The change uses the `content` attribute of a request object, which contains
bytes data. The `text` attribute converts the `content` (or `raw`) attribute
to a string of ascii. This doesn't work for unicode chars that can't be
converted to ascii.
Addresses openstax/cnx#291
> Write content to disk as bytes

- nebu/cli/get.py
- nebu/tests/cli/test_get.py
This code has been removed, because the `get` command will always want the
collated version (aka raw). Just ask for the non-collated form to begin with.
The comment that has been removed also notes that "this should never happen".
> Fix to always default to using the non-collated version

- nebu/cli/assemble.py
- nebu/tests/cli/test_assemble.py
"neb assemble" doesn't expect the output dir to exist and if it does, it
removes the whole directory.
Having an output directory specified by the user is going to be
problematic when we get to the later commands, mathify and pdf, because
the output directory has lots of symlinks to the input directory and
those aren't going to work when mounted in the docker container.
One of the ways to get this to work is to have the output directory as
the parent directory of the input directory.  That way, when the output
directory is mounted, the symlinks are going to work correctly.
> Don't clear the output dir in neb assemble

- nebu/cli/get.py
- nebu/tests/cli/test_get.py
This reverts #143, which is required because of how we are using a redirect to the archive's metadata. The route on archive unfortunately doesn't pass along the query string. (I'm not sure it pass along the query string, but I'm kinda on the fence about that.) This at any rate, reverts the change and puts comments in place to explain what's happening, so that I or someone else doesn't yank it out again. 😝
>  Revert defaulting to using the non-collated version

- nebu/models/binder.py
- nebu/models/document.py
- nebu/tests/models/test_document.py
Internal links to other parts of the book were not recognized by the
SingleHTMLFormatter.  If it linked to an image or an equation, after
baking, the correct link text (e.g. "Figure 2.10") can't be generated.
For internal links to work correctly, we need to prepend it with
"/contents/".  The SingleHTMLFormatter will look for the page ID to see
if it's within the book and rewrite the link accordingly.
> Fix internal links in "neb assemble"

- nebu/cli/mathify.py
- nebu/tests/cli/test_mathify.py
This implicit ordering of commands might be problematic as we're not
totally sure whether mathify should happen before or after baking.
Removing this code gives us some freedom to call mathify whenever we
want.
> Remove code to call assemble in mathify

- nebu/cli/assemble.py
- nebu/tests/cli/test_assemble.py
When I ran `neb assemble` after editing collection.xml to remove half of the
book for testing, I ran into this error:
```
karen@yachiyo:~/src/cnx-recipes$ ./venv.local/bin/neb assemble data/intermediate-algebra/raw/ data/intermediate-algebra/
This will remove 'data/intermediate-algebra/collection.assembled.xhtml', continue? [y/N]: y
Traceback (most recent call last):
File "./venv.local/bin/neb", line 10, in <module>
sys.exit(cli())
File "/home/karen/src/cnx-recipes/venv.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/home/karen/src/cnx-recipes/venv.local/lib/python3.6/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/home/karen/src/cnx-recipes/venv.local/lib/python3.6/site-packages/click/core.py", …
```
> Fix assemble when collection.xml doesn't use all modules

- .travis.yml
- Makefile
To avoid tagging and then getting rejected by pypi, we're running twine
check on travis so it will catch all the errors before we upload to
pypi.
> Add twine check on travis

- nebu/cli/main.py
- nebu/tests/cli/test_main.py
- setup.py
Remix of https://github.com/openstax/nebuchadnezzar/pull/156 but with a different implementation strategy. This time for real.
This can allow us to have neatly packaged utility scripts that will need to undergo less maintenance and testing by developer teams. These scripts could come from any dependency, but for right now, only from the new `neb-tasks` repo, which is added as an optional dependency to neb. These scripts, given the proper decorators, are added as commands in the Neb CLI.
This PR also adds sections to the CLI help output. Example:
Some things this might help us solve:
- https://github.com/openstax/cnx/issues/224
- Larissa mentioned it would also be helpful to have something to automate things like removing empty cnxml elements, so that CMs don't have to slog through so much …
> Add neb-tasks

- nebu/cli/main.py
- nebu/cli/ping.py
- nebu/tests/cli/test_ping.py
There is currently no quick way to determine whether a user has
permission to publish on a server or not, so this is to let us find out
without publishing anything.
Example usage:
```
neb ping -u manager -p xxxx content01
```
will respond with one of these messages:
```
Server error (status code: 500)
Internal Server Error
The server encountered an unexpected internal server error
(generated by waitress)
```
```
Publishing not allowed:
{"messages": [{"id": 5, "message": "Unauthorized", "error": "Nothing to see here."}]}
```
```
Bad credentials:
{"messages": [{"id": 5, "message": "Unauthorized", "error": "Nothing to see here."}]}
```
```
The user has permission to publish on this server.
```
> Add "ping" command to check credentials and permissions

- .travis.yml
- README.rst
- nebu/tests/cli/test_publish.py
This upgrades the code to run in Python 3.7 (and presumably 3.6) while still being compatible with Python 3.5.
For the most part the code itself runs fine in 3.x, but the tests needed tweaking with behavior changes in Python 3.7 to the `cgi` module's `parse_multipart` function, which started encoding the form data in 3.7.
> Upgrade codebase to work with Python >=3.5 <=3.7

- nebu/cli/ping.py
Noticed that user password is not hidden when using neb ping. Went ahead and made the tiny fix.
> Hide password input for neb ping

- .travis.yml
Couple reasons for this proposal:
- I checked with every CM to confirm they use python>=3.6
- Our dockerfile uses the python3.6 base image
- 3.6 is an objectively more fun number than 3.5
- I like python 3.6 f-strings and it's almost Christmas
> Upgrade python version in .travis.yml

- nebu/cli/assemble.py
In "neb assemble", we fetch exercises and then try to convert the math
using mathmlcloud.cnx.org.  It makes "neb assemble" very slow when there
are lots of exercises with math, e.g. hsphysics (col10002 on content04).
Since "neb assemble" is part of the bakery CLI, we can just leave the
math until the mathify step instead.  This speeds up "neb assemble" for
hsphysics by more than 50% (from 20m to 9m) on my machine.
---
See also https://github.com/openstax/mathify/pull/54
> Stop converting exercise math using mathmlcloud in assemble

- docs/changes.rst
- nebu/cli/get.py
- nebu/tests/cli/test_get.py
- nebu/tests/conftest.py
- requirements/main.txt
- requirements/test.txt
asyncio is one option we can take to speed up neb get. Brenda is working on using thread pools to do the same thing. We are planning to benchmark the two solutions for fun, learning, and profit for OpenStax.
Passes test for python 3.7 but fails tests for python 3.5 because it uses f-strings. Oops. There was some basic level of care taken to only use python 3.5 compatible asyncio syntax, however.
```bash
$ time neb get -r -d "/tmp/neb${RANDOM}" staging col12087 latest
Getting /tmp/neb8141  [###############################]  160/160
real	5m58.370s
user	0m47.899s
sys	0m3.422s
$ git switch async-get
$ time neb get -r -d "/tmp/neb${RANDOM}" staging col12087 latest
Getting /tmp/neb3457  [###############################]  186/186
real	0m17.408s
user	0m7.522s
sys	0m1.023s
$ cd /tmp/neb8141 && …
```
> Use asyncio for neb get

- docs/changes.rst
- nebu/cli/get.py
- nebu/tests/cli/test_get.py
The default requests limit is 8. Above 8-10, we start to see diminishing
returns from adding more requests concurrently. Timouts were raised,
since we aren't needing to catch server timeouts as frequently.
> Add requests limit and adjust timeouts

- docs/changes.rst
- nebu/cli/assemble.py
- nebu/tests/cli/test_main.py
- requirements/main.txt
Using 20 threads to fetch exercises for hsphysics (col10002 on
content04) reduces the time in "neb assemble" from 8m26s to 54s.
---
This branch is on top of the remove mathmlcloud PR #168 and depends on the threading code in cnx-epub openstax/cnx-epub#158. **Note: <- travis fails unless this is merged**
> Use 20 threads to fetch exercises in neb assemble

- nebu/cli/get.py
- nebu/tests/cli/test_get.py
The neb get command already uses the legacy url to get a collection's
metadata as part of its processing. This change adds a flag for the
command to save that metadata so that an invoker can utilize that data
if needed.
> Add flag for saving metadata to get command

- README.rst
- nebu/cli/_common.py
- nebu/cli/get.py
- nebu/cli/ping.py
- nebu/cli/publish.py
- nebu/tests/cli/test__common.py
While employing neb to work with a cnx stack installed using Vagrant, a couple of issues were found which this PR aims to address:
* Use of commands such as `get`, `publish`, and `ping` fail due to use of self-signed certificates
* The logic to construct archive URLs doesn't work (e.g. neb tries to reach archive-local.cnx.org instead of the desired archive.local.cnx.org)
> Improvements to better support local VM environments

- Dockerfile
- requirements/test.txt
Docker image size is slimmed from 837MB to 539MB. I also noticed that tests did not pass inside a container, so I added the necessary libraries for neb to function as expected in a container, including a JRE needed for xhtml validation.
Also updated the pytest minimum version because travis will accept nothing less than 4.6 now, it seems.
> Docker image maintenance

- nebu/models/binder.py
- nebu/models/utils.py
- nebu/tests/data/assembled_collection_for_git_workflow/README.md
- nebu/tests/data/assembled_collection_for_git_workflow/collection.assembled.xhtml
- nebu/tests/data/assembled_collection_for_git_workflow/m46882
- nebu/tests/data/assembled_collection_for_git_workflow/m46882.xhtml
- nebu/tests/data/assembled_collection_for_git_workflow/m46909
- nebu/tests/data/assembled_collection_for_git_workflow/m46909.xhtml
- nebu/tests/data/assembled_collection_for_git_workflow/m46913
- nebu/tests/data/assembled_collection_for_git_workflow/m46913.xhtml
- nebu/tests/data/assembled_collection_for_git_workflow/rebuild.py
- nebu/tests/data/collection_for_git_workflow/README.md
- nebu/tests/data/collection_for_git_workflow/collection.xml
- nebu/tests/data/collection_for_git_workflow/m46882/index.cnxml
- nebu/tests/data/collection_for_git_workflow/m46909/index.cnxml
- nebu/tests/data/collection_for_git_workflow/m46913/index.cnxml
- nebu/tests/data/collection_for_git_workflow/metadata.json
- nebu/tests/models/conftest.py
- nebu/tests/models/test_binder.py
- nebu/tests/models/test_document.py
- nebu/tests/models/test_resource.py
- nebu/tests/models/test_utils.py
- requirements/main.txt
Notes to help with code review:
* The core code changes in this PR are limited to [this commit](https://github.com/openstax/nebuchadnezzar/pull/189/commits/9518d96c9ed5366651a0490f78d2f50605fc543f) which implements the fallback logic
* There are a couple of commits that update dependencies for [cnxml](https://github.com/openstax/nebuchadnezzar/pull/189/commits/e1f991f87bca263b60ece92deaca4dbe3d42ad91) and [cnx-epub](https://github.com/openstax/nebuchadnezzar/pull/189/commits/a22c49c808ce50007c68990d06897cf444023132)
* The remainder of the commits are for test updates including [creating dedicated fixtures for git workflow](https://github.com/openstax/nebuchadnezzar/pull/189/commits/221f23b9a979e5f6f3131273fc21bf6482e82478) so we can test the differences between archive and git more …
> Add fallbacks to pull UUID from CNXML metadata

- nebu/models/binder.py
- nebu/tests/data/collection_for_bakedpdf_workflow/collection.xml
- nebu/tests/models/test_binder.py
A diff of the assembled book before and after the change:
```
4c4
<     <title>Principles of Economics</title>
---
>     <title>Principles of Macroeconomics</title>
20c20
<       <h1 data-type="document-title" itemprop="name">Principles of Economics</h1>
---
>       <h1 data-type="document-title" itemprop="name">Principles of Macroeconomics</h1>
```
> Ignore derived-from metadata when setting titles

- requirements/main.txt
This update adds a Polish license and makes an empty url attribute on a md:license tag resolve to None so that the default license will be used.
Note, we recently updated the default license to include the text '(ASSUMED)'. This might become a more visible change since at least two derived books have empty license urls.
> Update cnxml from 3.1.7 to 3.1.8
