nebu/cli/main.py
nebu/tests/cli/test_main.py

This provides a command to validate the contents of a litezip formatted directory.
Depends on #2

Add the Validate Command

---

.gitignore
README.rst

Provides instructions for installing this repo for CM's.

adds install instructions

---

README.rst

Because we were looking for this here but it was actually in a different repo

link to atom install documentation

---

docs/changes.rst
nebu/cli/main.py
nebu/tests/cli/test_main.py

This is mostly a stubbed out version of the logic. Refactoring will be required, but the logic is sound. The major thing to refactor will be the way the communication happens and the CLI output.

Add a publish command that communicates with a Press service

---

docs/changes.rst
nebu/cli/main.py

Fix atom config filepath to RNG file

---

nebu/tests/cli/test_main.py

don't compare lists where order is not important

---

.github/config.yml
.github/settings.yml

Configure staxly (probot) integration with this repo

---

docs/changes.rst
nebu/cli/main.py
nebu/tests/cli/test_main.py

this removes the default "latest" for collection version param

require collection version for get

---

nebu/cli/main.py

Remove the now untested and unused default version code

Require version

---

Makefile
docs/changes.rst
nebu/cli/main.py
nebu/tests/cli/test_main.py
nebu/tests/data/contents.json
nebu/tests/data/contents_old.json
nebu/tests/data/extras.json
nebu/tests/data/extras_old.json
nebu/tests/data/missing_zip.json

Switch from fetching from legacy to fetching from archive. Use the new `headVersion` info to warn and prompt if old version has been selected for download

Fetch from archive

---

.github/settings.yml

This enables squash commits for merging.

Use squash commits for merging

---

docs/changes.rst
nebu/_version.py
nebu/cli/main.py
nebu/tests/cli/test_main.py

Thought I'd give issue #16 an attempt since it is labeled help-wanted and it seemed like it would be good practice for me 😃 
My concerns with what I have right now:
- I couldn't manage to get timeout working properly, so `--version` stalls for 15 seconds or so if the user has no internet connection
- Not sure if pulling from pypi like that is 100% safe
- Uses regex to try to determine the current installed version of the user :(
Any suggestions?

Latest version suggestion if user version out of date

---

docs/changes.rst
nebu/cli/publish.py
nebu/tests/cli/test_publish.py

Fixes issue https://github.com/Connexions/cnx-press/issues/186

Add Basic Authentication for publishing

---

nebu/cli/get.py
nebu/cli/publish.py
nebu/cli/validate.py
nebu/tests/cli/test_get.py
nebu/tests/cli/test_validate.py

Addresses issue https://github.com/Connexions/nebuchadnezzar/issues/79

Append version to collection directory name

---

docs/changes.rst
nebu/cli/get.py

Seems "Introduction" as first modpage in a chapter need to be zero-prefix as well. Did that.

zero-number Introduction as well as Preface

---

docs/changes.rst
nebu/cli/get.py
nebu/tests/cli/test_get.py

add test for `get --output-dir` is outside cwd

---

README.rst

Creating on @reedstrm 's behalf

add libmagic install info to README

---

nebu/cli/publish.py
requirements/main.txt

Refactor only pub changed content

---

Jenkinsfile

This adds steps to auto-release the Python package to PyPI when a tag is created.

Add Jenkinsfile for auto releasing the package to PyPI

---

.github/settings.yml

Let's let the developers decide the best way to merge the changes.

Enable all github PR merging methods

---

nebu/cli/get.py

When using neb get on my machine, I get this error:
```
$ neb get prod col11562 1.23
Traceback (most recent call last):
File "/home/karen/src/nebuchadnezzar/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
chunked=chunked)
File "/home/karen/src/nebuchadnezzar/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
six.raise_from(e, None)
File "<string>", line 2, in raise_from
File "/home/karen/src/nebuchadnezzar/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
httplib_response = conn.getresponse()
File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
response.begin()
File "/usr/lib/python3.6/http/client.py", line 297, in begin
version, status, reason = self._read_status() …
```

Add retries to neb get by using session and adapter

---

docs/changes.rst
nebu/cli/get.py
nebu/tests/cli/test_get.py
nebu/tests/data/README.md
nebu/tests/data/mod_ascii_encoded.cnxml
nebu/tests/data/mod_utf8_encoded.cnxml

Based off of #148. This one is just for releasing without the beta changes.

Disregard decoded chars when detecting what's changed - Neb v9.0.2

---

docs/changes.rst
nebu/cli/get.py
nebu/tests/cli/test_get.py
nebu/tests/data/README.md
nebu/tests/data/mod_ascii_encoded.cnxml
nebu/tests/data/mod_utf8_encoded.cnxml

https://github.com/openstax/cnx/issues/273
To fully test that the changes in this PR work correctly to solve the issue, a test in the `cnx-automation` repo is sort of required, or running the manual test (in the issue) instead. The test in this very PR just tests the functionality indirectly, as a unit test.

Disregard decoded chars when detecting what's changed

---

docs/changes.rst
nebu/cli/assemble.py

Fixes https://github.com/openstax/cnx/issues/299
Note: I spent some time trying to write a test for this tiny change with no luck. At this time I decided it's not worth spending any more time on it. Hopefully I made the right call and this PR is okay as it is for such simple change.

Improve message when dir exists on assemble

---

Dockerfile

So we can run neb inside a docker container.

Add Dockerfile for nebuchadnezzar

---

requirements/main.txt

Refs https://github.com/openstax/rhaptos.cnxmlutils/pull/196

Pin rhaptos.cnxmlutils to 2.1.1

---

docs/changes.rst
requirements/main.txt

Refs https://github.com/openstax/rhaptos.cnxmlutils/pull/198 and https://github.com/openstax/cnx-epub/pull/179

Update the injected exercise HTML format

---

docs/changes.rst
requirements/main.txt

refs openstax/rhaptos.cnxmlutils#204

Include Error context when exercise has more than one link

---

docs/changes.rst
requirements/main.txt

Refs openstax/rhaptos.cnxmlutils#205

add data-type to code elements

---

docs/changes.rst
requirements/main.txt

refs openstax/rhaptos.cnxmlutils#206

:bug: fix the pattern used to match embedded exercises

---

docs/changes.rst
requirements/main.txt

Ensure all IDs are unique and remove randomly-generated IDs

---

docs/changes.rst
requirements/main.txt

update cnx-transforms, rhaptos.cnxmlutils to allow italics in titles

---

docs/changes.rst
requirements/main.txt

Refs https://github.com/openstax/cnx-recipes/issues/4781

Revert title patch

---

docs/changes.rst
requirements/main.txt

Cleanup html

---

nebu/models/binder.py
nebu/models/utils.py
nebu/tests/models/test_utils.py

This is part of the CNXbooks EPUB work
Refs openstax/enki#122 and https://github.com/openstax/ce/issues/1926

Fixes for generating epubs for CNX user books

---

Makefile
nebu/tests/cnxml/para.cnxml
nebu/tests/snapshots/test_converters/test_diffs/para.xhtml
nebu/xsl/cnxml-to-html5.xsl

refs https://github.com/openstax/ce/issues/2028

:bug: fix Para conversion for American Government 
